Missing ; detected by LLVM compiler on A100
./Uintah/src/Core/Parallel/Parallel.cc:582:64: error: expected ';' after expression
                << " per block: \t" << s_cuda_threads_per_block