* Reverted changes made in commit fd20ac4. * Added -fno-ipa-cp-clone.
This commit reverts to using default compilers on uintah-build, which
are currently GCC 8.3.0.

This compiler flag fixes GCC 8.3.0 build issues with optimization level
O3 resulting in undefined references such as the below:
 
/usr/bin/ld: lib/libCCA_Components_Models.so: undefined reference to
`void Uintah::OnDemandDataWarehouse::transferFrom<UintahSpaces::CPU,
UintahSpaces::HostSpace>(Uintah::DataWarehouse*, Uintah::VarLabel
const*, Uintah::ComputeSubset<Uintah::Patch const*> const*,
Uintah::ComputeSubset<int> const*,
Uintah::ExecutionObject<UintahSpaces::CPU, UintahSpaces::HostSpace>&,
bool, Uintah::ComputeSubset<Uintah::Patch const*> const*)'