add_arrow()   - put a conditional in so that arrows below SMALL_NUM = 1e-50 aren't drawn.   Prevously, it would try to draw these really small vectors and lockup   with
  (red square)
  ERROR: Module crashed with the following exception:
  ERROR: l>0.0 (file: ../src/Core/Geometry/Vector.h, line: 410)

   and you could never look at your first few timesteps worth of data.