* Replaced throw(ConsecutiveRangeSetException) with noexcept(false).
This commit updates C++ use to comply with C++17.

This replacement fixes C++17 build issues resulting in errors such as
the below:

../src/Core/Containers/ConsecutiveRangeSet.cc:159:4: error: ISO C++17
does not allow dynamic exception specifications
[-Wdynamic-exception-spec]
   throw(ConsecutiveRangeSetException)
../src/Core/Containers/ConsecutiveRangeSet.cc:159:4: note: use
'noexcept(false)' instead
   throw(ConsecutiveRangeSetException)

Note, dynamic exception specification (i.e., throw() and throw(typeid,
typeid, ...)) was deprecated in C++11.