Adopts GPU portability for all of the Arches-kokkos boundary condition code, as well as openMP support for some legacy code.
Expands use of parallel_for_unstructured to allow for streaming, and corrects omission of modifies datawarehouse calls for GPUs.
To prevent "undefined reference to" linker errors some functions were moved to headers as they had to be templated for portability.



Former-commit-id: a697b8255fedc7f5bc490faca4450ab10782347a